### ISSUE TITLE
Binder link

### ISSUE THREAD

**Issue by alex-s-gardner** [vdevauxchupin/ITS-LIVE-Downloader-Tracker#1]
I wonder if a binder link could be added similar to https://github.com/nasa-jpl/its_live that would allow someone to run your notebook without having to download the code.

**Comment by vdevauxchupin** [comment]
That's a good idea ! However I'm afraid that the 2GB of RAM from Binder will run out really quickly. Maybe I can write a "light" version which allows to download only small chunks of cubes, and if people are interested in bigger datacubes they can download the main code.

**Comment by vdevauxchupin** [comment]
I setup a Binder link. It should work, whether you use the files already downloaded as example, or if you select a new area. I couldn't find a solution for the RAM usage, so Binder users will have to keep the files' size reasonably small.

Let me know if you encounter any issue on the Binder !
